version: '3.2'
services:
  postgresql:
    image: "postgres:12"
    container_name: dev-local-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: JsVaf8tVOo
    ports:
      - 5432:5432
    volumes:
      - ./resources/docker/postgresql:/opt
      - ./resources/docker/data/docker-postgres-data:/var/lib/postgresql/data
  redis:
    image: "redislabs/rejson:latest"
    container_name: dev-local-redis
    ports:
      - 6379:6379
  rabbitmq:
    build: resources/docker/rabbitmq
    container_name: dev-local-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./resources/docker/data/docker-rabbitmq-data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog:latest
    container_name: dev-local-mailhog
    ports:
      - "8025:8025"